export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL'

export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL'

export const GET_HABITS = 'GET_HABITS'
export const GET_HABITS_SUCCESS = 'GET_HABITS_SUCCESS'
export const GET_HABITS_FAIL = 'GET_HABITS_FAIL'

export const CREATE_HABIT = 'CREATE_HABIT'
export const CREATE_HABIT_SUCCESS = 'CREATE_HABIT_SUCCESS'
export const CREATE_HABIT_FAIL = 'CREATE_HABIT_FAIL'
